version: "3.8"
services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - ./.data:/data/db
  firebase:
    image: itsmecoryhuebner/firebase-emulators:1.0.0
    environment:
      - GCP_PROJECT=demo-budget
    ports:
      - "4400:4400" # Emulator Hub
      - "4500:4500" # Other reserved port
      - "9099:9099" # Auth
      - "8083:8083" # UI
  grafana:
    image: grafana/grafana-enterprise
    restart: unless-stopped
    ports:
      - "3000:3000"
