name: Continuous integration
on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - packages/**
      - .github/workflows/node-pr.yml

jobs:
  change_validation:
    name: Change Validation
    runs-on: ubuntu-20.04
    steps:
      - name: Clone PR branch
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3

      - name: Get Node Version
        run: echo "NODE_VERSION=$(<.nvmrc)" >> $GITHUB_ENV

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npx nx affected -t lint --parallel=3

      - name: Test
        run: npx nx affected -t test --parallel=3
